preset: laravel
risky: true
enabled:
  - concat_with_spaces
disabled:
  - no_unused_imports
  - concat_without_spaces
finder:
  name: "*.php"
  not-name:
    - "*.blade.php"
    - index.php
    - server.php